-- Turnos EDS v0.8 - Persistencia segura por usuario
-- Ejecutar en Supabase SQL Editor.

create table if not exists public.turnos_eds_state (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace text not null default 'eds-40098',
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, workspace)
);

create table if not exists public.turnos_eds_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace text not null default 'eds-40098',
  version integer not null,
  state jsonb not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists turnos_eds_state_user_idx on public.turnos_eds_state(user_id);
create index if not exists turnos_eds_versions_user_idx on public.turnos_eds_versions(user_id);
create index if not exists turnos_eds_versions_workspace_version_idx on public.turnos_eds_versions(workspace, version desc);

alter table public.turnos_eds_state enable row level security;
alter table public.turnos_eds_versions enable row level security;

revoke all on table public.turnos_eds_state from anon, authenticated;
revoke all on table public.turnos_eds_versions from anon, authenticated;
grant select, insert, update, delete on table public.turnos_eds_state to authenticated;
grant select, insert, delete on table public.turnos_eds_versions to authenticated;
grant usage, select on sequence public.turnos_eds_versions_id_seq to authenticated;

-- Estado actual
create policy "turnos_state_select_own"
on public.turnos_eds_state for select to authenticated
using ((select auth.uid()) = user_id);

create policy "turnos_state_insert_own"
on public.turnos_eds_state for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "turnos_state_update_own"
on public.turnos_eds_state for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "turnos_state_delete_own"
on public.turnos_eds_state for delete to authenticated
using ((select auth.uid()) = user_id);

-- Historial de versiones
create policy "turnos_versions_select_own"
on public.turnos_eds_versions for select to authenticated
using ((select auth.uid()) = user_id);

create policy "turnos_versions_insert_own"
on public.turnos_eds_versions for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "turnos_versions_delete_own"
on public.turnos_eds_versions for delete to authenticated
using ((select auth.uid()) = user_id);
