create table if not exists public.turnos_eds_shared_state (
  workspace text primary key,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id) on delete set null
);

create table if not exists public.turnos_eds_shared_versions (
  id bigint generated by default as identity primary key,
  workspace text not null,
  version integer not null,
  state jsonb not null,
  note text,
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists turnos_eds_shared_versions_workspace_created_idx
  on public.turnos_eds_shared_versions (workspace, created_at desc);

alter table public.turnos_eds_shared_state enable row level security;
alter table public.turnos_eds_shared_versions enable row level security;

grant select on public.turnos_eds_shared_state to anon, authenticated;
grant insert, update, delete on public.turnos_eds_shared_state to authenticated;
grant select on public.turnos_eds_shared_versions to anon, authenticated;
grant insert, update, delete on public.turnos_eds_shared_versions to authenticated;
grant usage, select on sequence public.turnos_eds_shared_versions_id_seq to authenticated;

drop policy if exists shared_state_public_read on public.turnos_eds_shared_state;
create policy shared_state_public_read on public.turnos_eds_shared_state
for select to anon, authenticated using (workspace = 'principal');

drop policy if exists shared_state_auth_insert on public.turnos_eds_shared_state;
create policy shared_state_auth_insert on public.turnos_eds_shared_state
for insert to authenticated with check (workspace = 'principal');

drop policy if exists shared_state_auth_update on public.turnos_eds_shared_state;
create policy shared_state_auth_update on public.turnos_eds_shared_state
for update to authenticated using (workspace = 'principal') with check (workspace = 'principal');

drop policy if exists shared_state_auth_delete on public.turnos_eds_shared_state;
create policy shared_state_auth_delete on public.turnos_eds_shared_state
for delete to authenticated using (workspace = 'principal');

drop policy if exists shared_versions_public_read on public.turnos_eds_shared_versions;
create policy shared_versions_public_read on public.turnos_eds_shared_versions
for select to anon, authenticated using (workspace = 'principal');

drop policy if exists shared_versions_auth_insert on public.turnos_eds_shared_versions;
create policy shared_versions_auth_insert on public.turnos_eds_shared_versions
for insert to authenticated with check (workspace = 'principal');

drop policy if exists shared_versions_auth_update on public.turnos_eds_shared_versions;
create policy shared_versions_auth_update on public.turnos_eds_shared_versions
for update to authenticated using (workspace = 'principal') with check (workspace = 'principal');

drop policy if exists shared_versions_auth_delete on public.turnos_eds_shared_versions;
create policy shared_versions_auth_delete on public.turnos_eds_shared_versions
for delete to authenticated using (workspace = 'principal');
