-- Turnos EDS v1.0 - Persistencia completa con Supabase Auth + RLS
-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.turnos_eds_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace text not null default 'eds-40098',
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, workspace)
);

create table if not exists public.turnos_eds_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace text not null default 'eds-40098',
  version integer not null,
  state jsonb not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists turnos_eds_versions_user_workspace_created_idx
  on public.turnos_eds_versions (user_id, workspace, created_at desc);

alter table public.turnos_eds_state enable row level security;
alter table public.turnos_eds_versions enable row level security;

-- Revoca acceso amplio y concede solo operaciones vía rol autenticado.
revoke all on table public.turnos_eds_state from anon;
revoke all on table public.turnos_eds_versions from anon;
grant select, insert, update, delete on table public.turnos_eds_state to authenticated;
grant select, insert, update, delete on table public.turnos_eds_versions to authenticated;
grant usage, select on sequence public.turnos_eds_versions_id_seq to authenticated;

-- Políticas idempotentes: eliminar si ya existen y recrear.
drop policy if exists "turnos_state_select_own" on public.turnos_eds_state;
drop policy if exists "turnos_state_insert_own" on public.turnos_eds_state;
drop policy if exists "turnos_state_update_own" on public.turnos_eds_state;
drop policy if exists "turnos_state_delete_own" on public.turnos_eds_state;

drop policy if exists "turnos_versions_select_own" on public.turnos_eds_versions;
drop policy if exists "turnos_versions_insert_own" on public.turnos_eds_versions;
drop policy if exists "turnos_versions_update_own" on public.turnos_eds_versions;
drop policy if exists "turnos_versions_delete_own" on public.turnos_eds_versions;

create policy "turnos_state_select_own"
on public.turnos_eds_state for select
to authenticated
using (auth.uid() = user_id);

create policy "turnos_state_insert_own"
on public.turnos_eds_state for insert
to authenticated
with check (auth.uid() = user_id);

create policy "turnos_state_update_own"
on public.turnos_eds_state for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "turnos_state_delete_own"
on public.turnos_eds_state for delete
to authenticated
using (auth.uid() = user_id);

create policy "turnos_versions_select_own"
on public.turnos_eds_versions for select
to authenticated
using (auth.uid() = user_id);

create policy "turnos_versions_insert_own"
on public.turnos_eds_versions for insert
to authenticated
with check (auth.uid() = user_id);

create policy "turnos_versions_update_own"
on public.turnos_eds_versions for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "turnos_versions_delete_own"
on public.turnos_eds_versions for delete
to authenticated
using (auth.uid() = user_id);
